This change adds protection against rollover at high altitudes.
apache/mynewt-core pull request #2407
Opened 2020-11-03 20:18 UTC by supervillain101

Fix was provided by Bosch.

At high altitudes there is a potential for rollover in the compensate_pressure() function.  To prevent that, Bosch provided a fix with a divide by 10 in the affected code and then a multiply by 10 after to bring the final value back to the expected value.

2020-11-03 20:24 UTC, vrahane requested changes
Please write better commit messages. Rest looks fine.

2020-11-04 02:07 UTC, vrahane commented
@supervillain101 What I meant by that is, we generally write commit messages like this:

`sensors/bmp388: Adding protection against rollover at high altitudes.`

It gives a small description of the fix along with the module that you are changing.

2020-11-04 17:06 UTC, wes3 reviewed
Some unsolicited comments here. I prefer using parentheses so you do not need to think about associativity and precedence of operators. I think there should be parentheses like this: partial_data5 = (partial_data4 * (uncomp_data->pressure / 10)) / 512;

I thought that * and / have same precedence and are evaluated left to right but I could be wrong; I do not remember this stuff as I always use parentheses so I do not have to worry about it but I do not think you get the same answer.

Another thing: why was the value 10 chosen and why was uncomp_data->pressure chosen to divide? I would divide the larger number as opposed to the smaller number but maybe the pressure is generally larger than the other. One final note here: it is always better to divide by powers of 2 so if 8 works I would have chosen 8 :-)

2020-11-04 17:13 UTC, vrahane commented
I agree with what @wes3 is saying, it makes sense to use parenthesis above. 

![](https://media.geeksforgeeks.org/wp-content/uploads/20190708164646/Operators-Associativity-1.jpg)

2020-11-04 17:17 UTC, supervillain101 commented
@vrahane Changes made to parens and commit message.

2020-11-04 18:24 UTC, vrahane approved these changes
Looks good.

2020-11-04 19:15 UTC, merged